### ISSUE TITLE
Add Project and Milestones

### ISSUE THREAD

**Issue by hickeng** [hickeng/financial#40]
I've used the top of README.md for noting what I'm planning next, but this isn't a good task prioritisation mechanism. It also doesn't give a timeline view of when it'll be ready for certain use cases, aka Milestones.

I have the following milestones in mind:
- [x] Generate f8949
- [x] State support - with CA as prepop default
- [x] Toggle per-lot treatment
- [ ] Fees & broker errors accounted for
- [x] Extension filing - sufficient confidence to assess extension payment
- [x] Final filing
- [x] Excel support
- [x] Export/import - able to reconstruct the sheet fully from import of serialised form
- [x] CPA validated

Usage:
- [x] Add issues to milestones
- [x] Add milestones to Project as planned releases
- [x] Add link to Project to README

**Comment by hickeng** [comment]
https://github.com/users/hickeng/projects/2/views/2
