### ISSUE TITLE
Tracking issue importing into TurboTax

### ISSUE THREAD

**Issue by hickeng** [hickeng/financial#52]
TurboTax issues:
- [ ] [I have errors on Form 1099-B Worksheet Morgan Stanley Capital Asset Sales worksheet](https://ttlc.intuit.com/community/taxes/discussion/i-have-errors-on-form-1099-b-worksheet-morgan-stanley-capital-asset-sales-worksheet/00/3197065)
- [ ] [Form 8949 Column f Code N](https://ttlc.intuit.com/community/taxes/discussion/form-8949-column-f-code-n/00/3199783)
- [ ] [Why are my wash sales importing from my financial institution with adjustment code N instead of code W?](https://ttlc.intuit.com/turbotax-support/en-us/help-article/form-1099-b/wash-sales-importing-financial-institution-code-n/L9x7DdiyG_US_en_US)
- [ ] keep [problem entry updated](https://github.com/hickeng/financial/blob/main/problems.md#incorrect-code-n-in-form-8949-generated-by-turbotax)

**Comment by hickeng** [comment]
One of the issues is still open (unchecked above), and the last is deleted from their site although I'm still receiving email updates about it.

The comments for the first issue in the list indicate that deleting the data and re-importing resolve the problem. Confirmed by a member of the Turtle Pond.
